movie/movie/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

movie/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'

urlpatterns = [
    path('',views.fun,name='fun'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movie/movieapp/models.py
from django.db import models

# Create your models here.
class movies(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movie/movieapp/forms.py
from django import forms
from . models import movies
class movie_form(forms.ModelForm):
    class Meta:
        model=movies
        fields=['name','desc','year','img']

movie/movieapp/views.py
from django.shortcuts import render, redirect
from . models import movies
from . forms import movie_form
# Create your views here.
def fun(request):
    obj=movies.objects.all()
    context={'movie_list':obj

    }
    return render(request,'index.html',context)
def details(request,movie_id):

    obj=movies.objects.get(id=movie_id)
    return render(request,'details.html',{'movie':obj})
def add(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=movies(name=name,desc=desc,year=year,img=img)
        movie.save()

    return render(request,'add.html')
def update(request,id):
    movie=movies.objects.get(id=id)
    form=movie_form(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie=movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movie/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name"><br>
    <input type="text" name="desc" placeholder="description"><br>
    <input type="text" name="year" placeholder="enter the year"><br>
    <input type="file" name="img" placeholder="image"><br>
    <input type="submit">

</form>

</body>
</html>

movie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movies
  </a>
</nav>
{%block body%}
{%endblock%}
</body>
</html>

movie/templates/delete.html
<form method="POST">
    {% csrf_token%}
    are you sure to delete this movie?
    <input type="submit">
</form>

movie/templates/details.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-6">

<img src="{{movie.img.url }}" width=300 height=300><br>
        </div>
        <div class="col-md-6">
             <h2>{{movie.name}}</h2><br>
            <h4>{{movie.desc}}</h4><br>
<h4>{{movie.year}}</h4>
<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id%}">update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id%}">delete</a>

        </div>
    </div>
</div>

{% endblock %}

</body>
</html>

movie/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit">
</form>

movie/templates/index.html
{% extends 'base.html' %}
{%block body%}

<div class="container">
    <div class="row">
        {% for i in movie_list%}

        <div class="col-md-3">


            <div class="card" style="width: 17rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="150" height="300">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Details</a>

  </div>
</div>


        </div>
        {% endfor %}


    </div>
</div>
<div class="cotainer">
    <div class="row">
        <div class="col-md-4">

            <a  class="btn btn-success" href="/add">add</a>
                </div>
            </div>

    </div>
</div>


{% endblock%}